### ISSUE TITLE
Shows missing .js error for modules with index.js

### ISSUE THREAD

**Issue by TheSecurityDev** [AlexSergey/eslint-plugin-file-extension-in-import-ts#2]
If we have a local module like `module/index.js`, we can just import from `module` without needing the `/index.js` path, but this extension shows an error for that.

**Comment by hugebdu** [comment]
IMHO it should support [ignorePackages](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/extensions.md)

**Comment by AlexSergey** [comment]
> If we have a module like `module/index.js`, we can just import from `module` without needing the `/index.js` path, but this extension shows an error for that.

I tried to reproduce this behavior many times. For example:

```js
import { v4 as uuidv4 } from 'uuid';
```

or

```js
import module from 'abc';
```

and I didn't see any errors.

The same for fix mode:

```shell
eslint --ext .ts,.json src/
```

Could you provide me the code or the project to reproduce this bug?

**Comment by TheSecurityDev** [comment]
> > If we have a module like `module/index.js`, we can just import from `module` without needing the `/index.js` path, but this extension shows an error for that.
> 
> I tried to reproduce this behavior many times. For example:
> 
> ```js
> import { v4 as uuidv4 } from 'uuid';
> ```
> 
> or
> 
> ```js
> import module from 'abc';
> ```
> 
> and I didn't see any errors.
> 
> The same for fix mode:
> 
> ```shell
> eslint --ext .ts,.json src/
> ```
> 
> Could you provide me the code or the project to reproduce this bug?

I think it has to be a local module. I'll see if I can create a reproducible example later.

**Comment by TheSecurityDev** [comment]
I'm not using this module anymore, so I can't really provide anything I guess.

**Comment by AlexSergey** [comment]
Should be covered by:

https://github.com/AlexSergey/eslint-plugin-file-extension-in-import-ts/pull/6
