### ISSUE TITLE
Force the addition of /index.js suffix when importing directly from a folder

### ISSUE THREAD

**Issue by CarusoX** [AlexSergey/eslint-plugin-file-extension-in-import-ts#3]
I would like for the rule to have an extra option to also force the /index.js suffix on imports.

We can also provide the autofix

So basically this code would fail:

`import { something } from './someFolder';`

And the correct usage would be:

`import { something } from './someFolder/index.js';`

I can provide a PR for this if needed

**Comment by mesqueeb** [comment]
I agree that forcing to point at an index file is way less confusing and a good practice.

**Comment by AlexSergey** [comment]
@CarusoX, yes, sure, if you can make PR please, do it

**Comment by CarusoX** [comment]
This [PR](https://github.com/AlexSergey/eslint-plugin-file-extension-in-import-ts/pull/6) should do the trick
